import argparse
import os
import pickle
import re
import sys


WINDOWS_ABS_PATH = re.compile(r"^[a-zA-Z]:[\\/]")


def load_functions(path):
    with open(path, "rb") as pickle_file:
        functions = pickle.load(pickle_file)
    if not isinstance(functions, list) or not functions:
        raise ValueError("expected a non-empty function list")
    return functions


def contains_windows_path(value):
    if isinstance(value, str):
        return bool(WINDOWS_ABS_PATH.match(value))
    if isinstance(value, dict):
        return any(contains_windows_path(item) for item in value.values())
    if isinstance(value, (list, tuple)):
        return any(contains_windows_path(item) for item in value)
    return False


def validate(binary, stage):
    if stage == "feature":
        suffix = ".feature.pickle"
    elif stage in ("filtered", "typed"):
        suffix = ".filtered.pickle"
    else:
        suffix = ".pickle"
    path = binary + suffix
    if not os.path.isfile(path):
        return ["missing {}".format(path)], 0
    try:
        functions = load_functions(path)
    except Exception as error:
        return ["cannot load {}: {}".format(path, error)], 0

    errors = []
    source_count = 0
    for index, function in enumerate(functions):
        if not isinstance(function, dict):
            errors.append("function {} is not a dictionary".format(index))
            continue

        if stage == "normalized":
            if contains_windows_path(function):
                errors.append("function {} retains a Windows path".format(index))

        if stage in ("lineno", "filtered", "typed", "feature"):
            if function.get("src_path"):
                source_count += 1
                for field in ("src_file", "src_line"):
                    if field not in function:
                        errors.append("function {} lacks {}".format(index, field))

        if stage in ("filtered", "typed", "feature"):
            if function.get("seg_name") != ".text":
                errors.append("function {} is not in .text".format(index))
            if not function.get("src_path") or not function.get("src_file"):
                errors.append("function {} lacks source identity".format(index))
            if str(function.get("name", "")).startswith("sub_"):
                errors.append("function {} retains an autogenerated name".format(index))

        if stage in ("typed", "feature"):
            for field in ("abstract_args_type", "abstract_ret_type"):
                if field not in function:
                    errors.append("function {} lacks {}".format(index, field))

        if stage == "feature" and not isinstance(function.get("feature"), dict):
            errors.append("function {} lacks a feature dictionary".format(index))

        if len(errors) >= 20:
            errors.append("validation stopped after 20 errors")
            break
    if stage == "lineno" and source_count == 0:
        errors.append("no function has source line information")
    return errors, len(functions)


def main():
    parser = argparse.ArgumentParser(description="Validate one TikNib pipeline stage.")
    parser.add_argument("--input_list", required=True)
    parser.add_argument(
        "--stage",
        required=True,
        choices=("normalized", "lineno", "filtered", "typed", "feature"),
    )
    parser.add_argument("--failed_list", required=True)
    args = parser.parse_args()

    with open(args.input_list, "r") as input_file:
        binaries = [line.strip() for line in input_file if line.strip()]

    failed = []
    function_count = 0
    for binary in binaries:
        errors, count = validate(binary, args.stage)
        function_count += count
        if errors:
            failed.append(binary)
            print("[FAIL] {}".format(binary))
            for error in errors:
                print("  - {}".format(error))

    with open(args.failed_list, "w") as failed_file:
        if failed:
            failed_file.write("\n".join(failed) + "\n")
    print(
        "stage={} validated={} passed={} failed={} functions={}".format(
            args.stage,
            len(binaries),
            len(binaries) - len(failed),
            len(failed),
            function_count,
        )
    )
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
